<div style="padding:30px; color: white; background-color: #0071CD">
<center>
<img src="img/logoub.jpeg"></img>
<center>
<h1>Algorísmica Avançada 2021</h1>
<h2>Examen Parcial 2 - Avaluació contínua</h2>
</center>
</div>

In [1]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

In [2]:
import networkx as nx
import numpy as np
from matplotlib import pyplot as plt

### Funcions auxiliars

In [3]:
def is_prime(n):
    """
    Donat un enter 'n' retorna True si és un nombre primer o False si no ho és
    """
    if n < 2: 
         return False;
    if n % 2 == 0:             
         return n == 2
    k = 3
    while k*k <= n:
        if n % k == 0:
            return False
        k += 2
    return True

<div class="alert alert-success">
    <h1>Problema 1: Gold mine</h1>
    <p>Considereu una mina vertical en forma de graella $M$ de mida $H \times W$ on $H$ és l'alçada (profunditat) de la mina i $W$ és l'amplada. <br>
        Cada posició de la graella $M(i,j)$ té un valor enter indicant quant d'or hi ha en aquella casella.<br>
        Tenim una exploradora que vol recollir el <b>màxim d'or possible anant des de dalt de tot de la mina fins a la màxima profunditat possible</b>. <br>Pot començar en el punt que més li convingui i, al baixar al següent nivell, pot decidir fer-ho en una de les tres cel·les adjacents (o dos en el cas que es trobi en un marge).</p>    
     <img src="img/goldmine.png" width='50%'/><br>
    Implementeu una funció anomenada <b>gold_mine</b> que, usant <b>programació dinàmica</b>, retorni el valor màxim d'or que pot recollir l'exploradora.
</div>

In [42]:
def inferior_neighbors(M, y, x):
    neighs = []
    
    if x != 0:
        neighs.append((y+1, x-1))
        
    neighs.append((y+1, x))
    
    if x < len(M[0])-1:
        neighs.append((y+1, x+1))
        
    return neighs

def maximal_paths(M, memo):
    for y in range(len(M)-1):
        for x in range(len(M[0])):
            actual = memo[y][x]
            print(actual)
            print('')
            
            for nei in inferior_neighbors(M, y, x):
                memo_nei_value = memo[nei[0]][nei[1]]
                before_nei_value = M[nei[0]][nei[1]]
                new_nei_value = actual + before_nei_value
                
                memo[nei[0]][nei[1]] = max(memo_nei_value, new_nei_value)
                print(memo)
                print('')

    return memo

def find_max_path(memo):
    return max(memo[-1])

def gold_mine(M):
    """
    Retorna el valor màxim que pot obtenir l'exploradora.
    
    Params
    ======
    :M: Una matriu de nombre enters de tipus numpy.array
    
    Returns
    =======
    :gold: El valor total de l'or que pot recol·lectar.
    """
    memo = M.copy()
    
    min_paths = maximal_paths(M, memo)
    
    gold = find_max_path(min_paths)
    
    return gold

In [43]:
M = np.array([[1,2,3],
              [4,5,6],
              [3,2,0]])
gold_mine(M) # Retorna 11

1

[[1 2 3]
 [5 5 6]
 [3 2 0]]

[[1 2 3]
 [5 6 6]
 [3 2 0]]

2

[[1 2 3]
 [6 6 6]
 [3 2 0]]

[[1 2 3]
 [6 7 6]
 [3 2 0]]

[[1 2 3]
 [6 7 8]
 [3 2 0]]

3

[[1 2 3]
 [6 8 8]
 [3 2 0]]

[[1 2 3]
 [6 8 9]
 [3 2 0]]

6

[[1 2 3]
 [6 8 9]
 [9 2 0]]

[[1 2 3]
 [6 8 9]
 [9 8 0]]

8

[[ 1  2  3]
 [ 6  8  9]
 [11  8  0]]

[[ 1  2  3]
 [ 6  8  9]
 [11 10  0]]

[[ 1  2  3]
 [ 6  8  9]
 [11 10  8]]

9

[[ 1  2  3]
 [ 6  8  9]
 [11 11  8]]

[[ 1  2  3]
 [ 6  8  9]
 [11 11  9]]



11

In [ ]:
M = np.array([[1,2,3],
              [4,5,6],
              [3,2,0]])

M = np.array([[1,2,3],
              [6,6,6],
              [3,2,0]])

M = np.array([[1,2,3],
              [8,8,8],
              [10,9,0]])

M = np.array([[1,2,3],
              [4,5,6],
              [3,2,0]])

M = np.array([[1,2,3],
              [4,5,6],
              [3,2,0]])

M = np.array([[1,2,3],
              [4,5,6],
              [3,2,0]])

In [32]:
M = np.array([[53, 69, 49, 11],
              [ 4, 16, 51, 34],
              [64, 53, 41, 93],
              [30, 87, 58, 36],
              [38, 53, 10, 60],
              [92, 91, 91, 42],
              [89, 68, 55, 76],
              [45, 73, 97, 41],
              [15, 29, 48, 25],
              [53, 51, 40, 31]])

print(len(M)-1)
print(len(M[0]))

9
4


In [6]:
M = np.array([[53, 69, 49, 11],
              [ 4, 16, 51, 34],
              [64, 53, 41, 93],
              [30, 87, 58, 36],
              [38, 53, 10, 60],
              [92, 91, 91, 42],
              [89, 68, 55, 76],
              [45, 73, 97, 41],
              [15, 29, 48, 25],
              [53, 51, 40, 31]])
gold_mine(M) # Retorna 694

0

<div class="alert alert-success">
    <h1>Problema 2: Prime Ring </h1>
    <p>Disposem de nombres enters de $1,\dots,N$ que volem col·locar en un cercle de forma que, per a qualsevols dos nombres adjacents, la seva suma sigui un nombre primer. <br>        
        Implementeu una funció anomenada <b>prime_ring</b> que, donat un valor enter $N$ retorni, si existeix, una configuració del cercle usant <b>backtracking</b>.<br>
        Observeu una de les solucions per a $N=8$ a continuació. Com podeu veure, totes les parelles de veïns tenen com a suma un nombre primer: <br><br>$$1+2,\quad 2+3,\quad 3+8,\quad 8+5,\quad 5+6,\quad 6+7,\quad 7+4,\quad 4+1$$ són nombres primers.
        <img src="img/prime_ring.png" width='20%'/>
        Hi ha moltes solucions possibles, podeu retornar-ne una qualsevol. </p><br>
        Us donem implementada la funció <b>is_prime</b> que comprova si un nombre és primer o no.    
</div>

In [7]:
# Exemple d'us
print(is_prime(1+8))
print(is_prime(3+10))

False
True


In [26]:
def prime_ring_backtracking(N, board):
    if(len(board) == N):
        if(is_prime(board[-1] + board[0])):
            return board
        return False
    
    for i in range(1, N+1):
        if(len(board) == 0):
            board.append(i)
        
        elif i not in board:
            before_item = board[-1]
            
            if(is_prime(before_item + i)):
                board.append(i)
                
                if prime_ring_backtracking(N, board):
                    return board
                
                board.pop()
    return False

def prime_ring(N):
    """
    Col·loca els nombres de 1 a N en un cercle de tal forma que dos nombres adjacents, la seva suma, sigui un nombre primer.
    
    Params
    ======
    :N: El nombre màxim que posarem al cercle.
    
    Returns
    =======
    :board: Una llista que representa el cercle. Pot començar en qualsevol dels elements. En el cas que no existeixi solució, retorna False.
    """
    board = []
    
    board = prime_ring_backtracking(N, board)
    
    return board

In [27]:
prime_ring(5) # Retorna False

False

In [28]:
prime_ring(8) # Una de les solucions possibles és [1, 2, 3, 8, 5, 6, 7, 4]

check
check
check
check
check
check
check


[1, 2, 3, 8, 5, 6, 7, 4]

In [29]:
prime_ring(12) # Una de les solucions possibles és [1, 2, 3, 4, 7, 6, 5, 12, 11, 8, 9, 10]

check
check
check
check
check
check
check
check
check
check
check


[1, 2, 3, 4, 7, 6, 5, 12, 11, 8, 9, 10]

In [30]:
for i in range(2, 13):
    print(f"N={i:<2}:",prime_ring(i))

check
N=2 : [1, 2]
N=3 : False
check
check
check
N=4 : [1, 2, 3, 4]
N=5 : False
check
check
check
check
check
N=6 : [1, 4, 3, 2, 5, 6]
N=7 : False
check
check
check
check
check
check
check
N=8 : [1, 2, 3, 8, 5, 6, 7, 4]
N=9 : False
check
check
check
check
check
check
check
check
check
N=10: [1, 2, 3, 4, 7, 6, 5, 8, 9, 10]
N=11: False
check
check
check
check
check
check
check
check
check
check
check
N=12: [1, 2, 3, 4, 7, 6, 5, 12, 11, 8, 9, 10]
